### ISSUE TITLE
Implement HashSet, BitArray, Stack, Queue

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Frameworks#11]
Create separate project for collections

Related issues: 
 * Stack and Queue - bridgedotnet/Bridge#99
 * BitArray - bridgedotnet/Bridge#360
 * HashSet - bridgedotnet/Bridge#361 (it is also about HashTable which is not implemented yet)

**Comment by DaniilVeriga** [comment]
[Bridge.Collections](https://www.nuget.org/packages/Bridge.Collections) has been released.
