### ISSUE TITLE
jQuery2 events does not have overloads supporting the event parameter itself

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Frameworks#16]
This was reported here: [How to use e.PreventDefault in key down?](http://forums.bridge.net/forum/general/extensions-and-plugins/707)

Solution for Bridge 1.9/current didn't match (for some reason) the solution for Bridge 1.8.

The solution for Bridge 1.9+ is posted [here](http://forums.bridge.net/node/713).
The solution for Bridge 1.8- updates the solution above with that is posted [here](http://forums.bridge.net/node/715).

1.8- additional solution fits well on 1.9+. (forwards compatible)

**Comment by LeonidVeriga** [comment]
Many thanks to @erdomke for this great pull request and contribution.
