### ISSUE TITLE
jQuery Template Bug - & instead of $

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Frameworks#30]
https://github.com/bridgedotnet/Frameworks/blob/master/jQuery2/Ajax/HelperFunctions.cs

Hi I have reproduced an issue I am seeing using the Param function in jQuery
http://live.bridge.net/#9f62a426ea8b07d33d53

`var url = &.param(parameters);`

instead of

`var url = $.param(parameters);`

**Comment by maverix** [comment]
https://github.com/bridgedotnet/Frameworks/pull/31

**Comment by fabriciomurta** [comment]
This is most likely related to bridgedotnet/Bridge#796.

**Comment by maverix** [comment]
It looks like a straight forward case of the wrong text inside the Template Attribute

[Template("&.param({0})")]

**Comment by DaniilVeriga** [comment]
The pull request (#31) has been merged. The fix will go to the next Bridge.jQuery release - 2.9.0.
