### ISSUE TITLE
Bridge.Framework solution

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Frameworks#33]
* Create a separate **Bridge.Framework.sln** in **Frameworks** repo.
* Use Bridge nuget packages (**Bridge.Core** and **Bridge.Html5**) to avoid referencing projects from external repos.
* Add **CommonAssemblyInfo.cs** to reuse `[AssemblyCompany]` and `[AssemblyCopyright]`
* Normalize EOLs in Bridge repo way
* [#43] Bridge.Collections to use Bridge package instead of call Bridge.Builder.exe fro Bridge repo
* Nuget packages for Frameworks

**Comment by geoffreymcgill** [comment]
Some of features have been implemented in #43.
