### ISSUE TITLE
jQuery.Extend incorrect output ?

### ISSUE THREAD

**Issue by nmyvision** [bridgedotnet/Frameworks#4]
the following code is only outputting the first element:

`jQuery.Extend( new {}, item.defaultSettings , item.questionSettings );`

outputs:

`$.extend({ },item.defaultSettings)`

expecting:

`$.extend({ },item.defaultSettings , item.questionSettings)`

**Comment by DaniilVeriga** [comment]
Thank you for the reporting that! Fixed, as well as other appearances with `params object[]`. 

It goes to the next public release. You can also update from GitHub and build from sources.

**Comment by geoffreymcgill** [comment]
With some luck this will be in the jQuery release tomorrow. That is the plan anyways.

**Comment by DaniilVeriga** [comment]
Bridge.jQuery 2.1.0 has been released with the fix.
