### ISSUE TITLE
Bridge.Collections Stack invalid array length error

### ISSUE THREAD

**Issue by matthew-lake** [bridgedotnet/Frameworks#42]
Using `Stack<int>` from `Bridge.Collections` I receive a Javascript error `RangeError: invalid array length` on pushing a value to the stack. Drilling down, this appears to be a problem in this section:

```
push: function (item) {
    if (this._size === this._array.length) {
        var localArray = { v: this._array };
        Bridge.Array.resize(localArray, (this._array.length === 0) ? Bridge.Collections.Stack$1(T).defaultCapacity : ((2 * this._array.length) | 0), null);
        this._array = localArray.v;
    }
    this._array[Bridge.identity(this._size, (this._size = (this._size + 1) | 0))] = item;
    this._version = (this._version + 1) | 0;
}
```
in `bridge.collections.js`. Specifically, `Bridge.Collections.Stack$1(T).defaultCapacity` is undefined.

The problem appears to be solved by substituting this with `Bridge.Collections.Stack$1(T).DefaultCapacity`.

It's not 100% clear to me if this is specifically a problem with `Stack` in `Bridge.Collections`, but I have not noticed it elsewhere. I have included a minimal reproduction that I tested on 2 computers.

[BridgeStackTest.zip](https://github.com/bridgedotnet/Frameworks/files/223670/BridgeStackTest.zip)

**Comment by DaniilVeriga** [comment]
Thank you for the report! We will investigate.

**Comment by LeonidVeriga** [comment]
Fixed in Bridge.Collections 1.2.1
