### ISSUE TITLE
Questions on publishing framework binding by community?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [bridgedotnet/Frameworks#47]
When writing a framework binding (C#-wrapper) for some javascript framework, how do advise the community members to proceed? Should we make a pull request to this repo or make our own repo? I have seen others publishing their bindings as their own repo such as Bridge.React and Bridge.Pixi but neither the main website of Bridge.NET nor this repo give links to their repositories as I only stumbled across these bindings by chance! 
IMO the best is to have the third-party frameworks page on [Bridge.NET](http://bridge.net/) to link to all other known bindings repo's. What do you think?

**Comment by geoffreymcgill** [comment]
Hi @Zaid-Ajaj, 

Welcome to the Bridge community and thanks for contacting us.

> IMO the best is to have the third-party frameworks page on Bridge.NET to link to all other known bindings repo's. What do you think?

Yes, absolutely agreed. This is something we've talked about in the past, but we will get to work on this right away. 

I'd say for now, if you create a binding library, make an announcement in the Bridge Forums (http://forums.bridge.net/). We will create a list somewhere of all 3rd party binding libraries.

**Comment by Zaid-Ajaj** [comment]
@geoffreymcgill Thanks alot for the quick answer, I will share my work as soon as I make the repo!
