### ISSUE TITLE
Is there has demo code for jquery.each function

### ISSUE THREAD

**Issue by weightbomb** [bridgedotnet/Frameworks#50]
such as this

$("div").each(function(){
     var item = $(this);
      // do something for item
});

**Comment by michaelcheers** [comment]
@weightbomb, You mean something like [this](http://live.bridge.net/#8ca563102ea5af555e0f06bf39545e45).

**Comment by vladsch** [comment]
`var item = new jQuery(Script.Write<object>("this"));` 
can be replaced by
`var item = jQuery.This;`

http://live.bridge.net/#9075bfb4ab236b5ff1aa4a18ab9605f0

**Comment by michaelcheers** [comment]
@vladsch, I've never used Bridge Jquery before.

**Comment by weightbomb** [comment]
@vladsch   thanks very much.   that is what i want to solve.
