### ISSUE TITLE
JQuery FadeTo should take a double opacity value

### ISSUE THREAD

**Issue by caesay** [bridgedotnet/Frameworks#52]
`jQuery.FadeTo(int duration, int opacity)`

The `opacity` parameter should be a double so you can specify a partial opacity (e.g. 0.5)

**Comment by geoffreymcgill** [comment]
Yes, agreed. There's likely several other locations where the type should be updated from **int** to **double**. 

We should be able to make this change and release quickly.

**Comment by geoffreymcgill** [comment]
Fixed and will be available with the next public release of **Bridge.jQuery**.
