### ISSUE TITLE
Bridge.Collections 1.3.3 not compatible with Bridge 15.7

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Frameworks#56]
The current nuget package available for Bridge.Collections (1.3.3) was compiled using Bridge 15.3. As a result, the JS file embedded in the Bridge.Collections assembly is not compatible with the recent changes to array creation in 15.7. A new nuget package that contains assemblies built with Bridge 15.7 is needed to be able to use Bridge.Collections with the latest version of Bridge.

**Comment by geoffreymcgill** [comment]
Thanks for bringing this to our attention. We will update all the Bridge Framework projects and release new NuGet packages. Should be complete within 24 hours (or less).

**Comment by ddaspit** [comment]
Excellent. Thank you for the quick response.

**Comment by geoffreymcgill** [comment]
Hi @ddaspit – Can you make a [Deck](http://deck.net) sample that demonstrates a failing scenario?

I've been running tests locally, but I just want to double check your case is working before closing this issue.

**Comment by ddaspit** [comment]
[Here](http://deck.net/56b72a2e12dddabdf460709038a7ed6b) is a simple example.

**Comment by geoffreymcgill** [comment]
Should be working now. 

Bridge.Collections 1.3.4 has been [released](nuget.org/packages/bridge.collections) to NuGet.

Hope this helps.
