### ISSUE TITLE
License for Bridge.Collections 1.3.3

### ISSUE THREAD

**Issue by anatsegev** [bridgedotnet/Frameworks#57]
Hi,

I'm using Bridge.Collections nuget:
https://www.nuget.org/packages/Bridge.Collections/

The link to license there is broken.

What license does it use? Apache 2.0 or MIT?
Other bridge components use Apache 2.0 but in license in the github repository for bridgedotnet/frameworks is MIT.

Thanks,
Anat

**Comment by geoffreymcgill** [comment]
Hi @anatsegev – Thanks for bringing this to our attention. Looks like the old MIT license was never updated.

I've applied the Apache 2.0 license to the [Frameworks](https://github.com/bridgedotnet/Frameworks) repo.

**Comment by geoffreymcgill** [comment]
As of Bridge v16.0, the **Bridge.Collections** is no longer being published and all functionality from **Bridge.Collections** is now available directly from the **Bridge** package within the **System** namespace. 

## See Also

* https://github.com/bridgedotnet/Bridge/issues/2730
