### ISSUE TITLE
bridge.collections.d.ts not embedded

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Frameworks#62]
The **bridge.collections.d.ts** file is not being embedded in the **Bridge.Collections** assembly and therefore is not being emitted to the `output` location in end user projects.

The following `generateTypeScript` config is required in the **bridge.json** config file of the  **Bridge.Collections** project:

```js
"generateTypeScript": true
```

Temp gist of [bridge.collections.d.ts](https://gist.github.com/geoffreymcgill/eb76027eada2f672f0814f2c2c8cb71b).

**Comment by GeneralGDA** [comment]
It looks like every interface in the gist contains redundant prefix "Bridge.Collections": all of them are already in the  Bridge.Collections module.

**Comment by geoffreymcgill** [comment]
As of Bridge v16.0, the **Bridge.Collections** is no longer being published and all functionality from **Bridge.Collections** is now available directly from **Bridge** package in the **System** namespace.
