### ISSUE TITLE
No /// <reference path="./bridge.collections.d.ts" /> in the TS output.

### ISSUE THREAD

**Issue by GeneralGDA** [bridgedotnet/Frameworks#64]
I use Bridge.Collections in my project. The TypeScript output lacks " /// <reference path="./bridge.collections.d.ts" /> " directives.

**Comment by geoffreymcgill** [comment]
As of Bridge v16.0, the **Bridge.Collections** is no longer being published and all functionality from **Bridge.Collections** is now available directly from **Bridge** package in the **System** namespace.
