### ISSUE TITLE
Bridge.Html5.Console.Warn gets transpiled as "console.Warn" with a capital W

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Frameworks#69]
### See Also 
* https://github.com/bridgedotnet/Bridge/issues/2936

**Comment by TriEdgeAI** [comment]
Are you going to be releasing the NuGet package with this soon?

**Comment by geoffreymcgill** [comment]
@TriEdgeAI we will release a new version of the package at some point within the next 12 hours.

**Comment by geoffreymcgill** [comment]
The package **Bridge.Html5.Console* version 1.0.4 has been published to NuGet. 

https://www.nuget.org/packages/bridge.html5.console

Hope this helps.

**Comment by TriEdgeAI** [comment]
<3
