### ISSUE TITLE
Missing metadata of Librarys

### ISSUE THREAD

**Issue by coddoge** [bridgedotnet/Frameworks#85]
I'm a C# developper, and now new to Bridge.Net.

About refection, got some problems.

Knowed Bridge.Net's reflection working dependence by metadata `*.meta.js`.  

Based on `bridge.meta.js` all build-in types's and my project assembly reflection working fine.

When i install `Bridge.Html5` version `17.3.0` from NuGet and build project
I can't find metadata in output path. 
And the code `typeof(Bridge.Html5.HTMLDivElement).GetMembers()` working not expected.
Its returned a empty array.

No just `Bridge.Html5`, all retyped package from NuGet seem missing metadata too.
e.g. `Retyped.ace` version `0.1.6733`
In my project, `AceAjax.Editor` as a class member (prop or field) , if reflection the class will get a
error  ` <AceAjax> is not defined` in `myproject.meta.js`.
Now i have to change the member define to `object` as workaround.
every time to use it i have to cast type in method body. that so terrible.

How to include library's metadata to let reflection function all working fine?
Or now i in a wrong way?

**Comment by samuelGrahame** [comment]
Hey Coddoge, I got your email.
Bridge.HTML5 - a library that gives you access to JavaScript objects in c# - this library doesn't exist on the browser. for instance - var x = new HTMLDivElement();
actually is just calling - document.createElement('div');

same thing goes for the Retyped libraries. These are libraries in c#. But are not included on the browser. only the javascript files are. it is a way of accessing JavaScript libraries in visual studio. only c# libraries that are written with bridge will have reflection.

**Comment by coddoge** [comment]
Hey samuelGrahame, Thank you for reply.
I must point out my issue have 2 problem.
The problem1, missing metadata of libraries is optional.

But problem 2 blocked me forward, and let me confused.
I just reflection in my assembly. 

To reproduce: Create a bridge project, install package `Retyped.ace` and run below code will generate a script error `AceAjax is not defined`.

```
public class App
{
    private static Retyped.ace.AceAjax.Editor editor;

    public static void Main()
    {
        var members = typeof(App).GetMembers();
    }
}
```
But i find a workaround:

```
public class App
{
    private static object editor; // define the member as object

    public static void Main()
    {
        var member = typeof(App).GetMembers(); // reflection is working fine

        var div = new dom.HTMLDivElement();
        dom.window.document.body.appendChild(div);
        editor = ace.ace2.edit(div); // boxing it
    }

    public void SomeMethod()
    {
        var input = ((ace.AceAjax.Editor)editor) // and unbox everywhere (so terrible)
            .getValue();
    }
}
```

May be i should post issue to bridge.net instead of  here.

**Comment by coddoge** [comment]
Repost to [Bridge#3724](https://github.com/bridgedotnet/Bridge/issues/3724)
